import {
  FaCss3,
  FaDocker,
  FaGit,
  FaGithub,
  FaHtml5,
  FaInstagram,
  FaJava,
  FaJs,
  FaLinkedin,
  FaMedium,
  FaPython,
  FaReact,
  FaTelegram,
} from "react-icons/fa";
import { FaAws } from "react-icons/fa6";
import { BiLogoPostgresql } from "react-icons/bi";
import { BsFileEarmarkExcelFill } from "react-icons/bs";
import {
  SiExpo,
  SiGeeksforgeeks,
  SiIntellijidea,
  SiKubernetes,
  SiLeetcode,
  SiMysql,
  SiPostman,
  SiRedux,
  SiSpring,
  SiSpringboot,
  SiTailwindcss,
  SiUpwork,
  SiX,
} from "react-icons/si";
import { TbBrandReactNative } from "react-icons/tb";
import { VscVscode } from "react-icons/vsc";

export const iconMap = {
  aws: FaAws,
  css: FaCss3,
  docker: FaDocker,
  excel: BsFileEarmarkExcelFill,
  expo: SiExpo,
  geeksforgeeks: SiGeeksforgeeks,
  git: FaGit,
  github: FaGithub,
  html: FaHtml5,
  instagram: FaInstagram,
  intellij: SiIntellijidea,
  java: FaJava,
  javascript: FaJs,
  kubernetes: SiKubernetes,
  leetcode: SiLeetcode,
  linkedin: FaLinkedin,
  medium: FaMedium,
  mysql: SiMysql,
  postgresql: BiLogoPostgresql,
  postman: SiPostman,
  python: FaPython,
  react: FaReact,
  reactnative: TbBrandReactNative,
  redux: SiRedux,
  spring: SiSpring,
  springboot: SiSpringboot,
  tailwind: SiTailwindcss,
  telegram: FaTelegram,
  upwork: SiUpwork,
  vscode: VscVscode,
  x: SiX,
};
